include: package:pedantic/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

# Customize rules
#
# linter:
#   rules:
#     camel_case_types: true
#     omit_local_variable_types: false
#     prefer_collection_literals: true
#     unnecessary_new: false