name: notes_firebase_ddd
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  dartz: ^0.9.2
  firebase_auth: ^0.18.1+2
  firebase_core: ^0.5.0+1
  flutter_bloc: ^6.0.6
  freezed_annotation: ^0.12.0
  google_sign_in: ^4.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  freezed: ^0.12.2
  pedantic: ^1.9.2

flutter:
  uses-material-design: true
